// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	CheckIn   time.Time
	CheckOut  time.Time
	UserID    string
	RoomID    string
}

type Room struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RoomName    string
	Description sql.NullString
	Price       string
	MaxGuests   int32
}

type User struct {
	ID              string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FullName        string
	Email           string
	Phone           sql.NullString
	Username        string
	Password        string
	ApiKey          string
	ApiKeyExpiresAt time.Time
}

type UsersToken struct {
	ID                    string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AccessTokenExpiresAt  time.Time
	RefreshToken          string
	RefreshTokenExpiresAt time.Time
	UserID                string
}
