// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rooms.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (id, created_at, updated_at, room_name, description, price, max_guests)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateRoomParams struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RoomName    string
	Description sql.NullString
	Price       string
	MaxGuests   int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RoomName,
		arg.Description,
		arg.Price,
		arg.MaxGuests,
	)
	return err
}

const getAllRooms = `-- name: GetAllRooms :one

SELECT id, updated_at, room_name, description, price, max_guests
FROM rooms
`

type GetAllRoomsRow struct {
	ID          string
	UpdatedAt   time.Time
	RoomName    string
	Description sql.NullString
	Price       string
	MaxGuests   int32
}

func (q *Queries) GetAllRooms(ctx context.Context) (GetAllRoomsRow, error) {
	row := q.db.QueryRowContext(ctx, getAllRooms)
	var i GetAllRoomsRow
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.RoomName,
		&i.Description,
		&i.Price,
		&i.MaxGuests,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one

SELECT id, updated_at, room_name, description, price, max_guests
FROM rooms
WHERE id = $1
`

type GetRoomByIDRow struct {
	ID          string
	UpdatedAt   time.Time
	RoomName    string
	Description sql.NullString
	Price       string
	MaxGuests   int32
}

func (q *Queries) GetRoomByID(ctx context.Context, id string) (GetRoomByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i GetRoomByIDRow
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.RoomName,
		&i.Description,
		&i.Price,
		&i.MaxGuests,
	)
	return i, err
}
